import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/lib/SessionProvider";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Need this async for sessionprov.
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Get the sessionData and provide it to the sessionprov.
  const sessionData = await auth.api.getSession({
    headers: await headers(),
  });



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={sessionData?.session ?? null} user={sessionData?.user ?? null}>
          {/* Also put navbar inside here! */}
          
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
